//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.21 at 10:39:06 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.com.rca.studies/spring/soapws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package studies.rca.com.soap.spring.soapws;
