//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.25 at 04:16:20 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com.rca.spring.exam/divinirakiza/soapws/suppliers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package exam.spring.rca.com.divinirakiza.soapws.suppliers;
